---
- name: Get InfluxDB's installer
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.7.9_amd64.deb
    dest: /home/{{ username }}/InfluxDB.deb
    checksum: sha256:02759d70cef670d336768fd38a9cf2f046a1bf40618be78ba215e7ce75b5075f

- name: Install the .deb file
  apt:
    deb: /home/{{ username }}/InfluxDB.deb

- name: Start the service!
  service:
    name: influxdb
    state: started