apiVersion: 1

# Config doc: https://grafana.com/docs/grafana/latest/features/datasources/influxdb/

datasources:
  - name: Auto_telegrafDB
    type: influxdb
    access: proxy
    database: telegraf
    url: http://localhost:8086
    jsonData:
      httpMode: GET

# Uncomment me if needed!
  # - name: Auto_nagfluxDB
  #   type: influxdb
  #   access: proxy
  #   database: nagflux
  #   url: http://localhost:8086
  #   jsonData:
  #     httpMode: GET