---
- hosts: visualizer_system
  remote_user: vagrant
  become: true
  become_method: sudo

  # Call each role involved in the installation process
  roles:
    - Grafana
    - InfluxDB
    - Telegraf