---
- name: Download the Grafana .deb file
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_6.5.2_amd64.deb
    dest: /home/{{ username }}/Grafana.deb
    checksum: sha256:af6592f379bd4b91b202f4845c31e79e0faeff1b4b1f12cbbb720a8980f2edd7
  # when: inventory_hostname == "host_a"

- name: Get Grafana's dependencies
  apt:
    name: "{{ grafana_deps }}"
    state: present

- name: Install the .deb file
  apt:
    deb: /home/{{ username }}/Grafana.deb

# - name: Reload systemd to let it pick config changes
#   systemd:
#     daemon_reload: yes

- name: Start Grafana
  service:
    name: grafana-server
    state: started

- name: Enable Grafana at boot
  service:
    name: grafana-server.service
    enabled: yes

- name: Copy the provisioning through InfluxDB
  copy:
    src: ./roles/Grafana/templates/InfluxDB_provisioning.yaml
    dest: /etc/grafana/provisioning/datasources/InfluxDB.yaml
    owner: root
    group: grafana
    mode: "0640"
